---
- name: Download WordPress
  get_url:
    url: https://wordpress.org/wordpress-5.7.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/
    remote_src: yes
  become: true

- name: Copy wp-config.php
  copy:
    src: "{{ wp_installation_path }}/wp-config-sample.php"
    dest: "{{ wp_installation_path }}/wp-config.php"
    remote_src: yes
  become: true

- name: Set Database Settings in wp-config.php
  replace:
    path: "{{ wp_installation_path }}/wp-config.php"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.value }}"
    backup: yes
  become: true
  with_items:
    - { regexp: "database_name_here", value: "{{ wp_db_name }}" }
    - { regexp: "username_here", value: "{{ wp_db_user }}" }
    - { regexp: "password_here", value: "{{ wp_db_password }}" }
    - { regexp: "localhost", value: "{{ mysql_host }}" }


