---
- name: Create MySQL Repo File
  copy:
    dest: /etc/yum.repos.d/mysql-community.repo
    content: |
      [mysql56-community]
      name=MySQL 5.6 Community Server
      baseurl=https://repo.mysql.com/yum/mysql-5.6-community/el/7/$basearch/
      enabled=1
      gpgcheck=1
      gpgkey=https://repo.mysql.com/RPM-GPG-KEY-mysql
  become: true

- name: Install Packages for Database Server
  yum:
    name: "{{ item }}"
    state: latest
  become: true
  with_items:
    - mysql-community-server
    - MySQL-python

- name: Starter MySQL Service
  service:
    name: mysqld
    state: started
    enabled: yes
  become: true

- name: Create WordPress Database
  mysql_db:
    name: "{{ wp_db_name }}"
    login_user: root
    state: present
  with_items:
    - "{{ mysql_host }}"
  become: true

- name: Copy my.cnf file
  template:
    src: templates/my.cnf.j2
    dest: /etc/my.cnf
  become: true
  notify:
    - restart mysql

- name: Create MySQL User for WordPress
  mysql_user:
    login_user: root
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present
  become: true
